// <auto-generated />
using System;
using Fluxo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fluxo.Infrastructure.Migrations
{
    [DbContext(typeof(FluxoDbContext))]
    partial class FluxoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fluxo.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Balance = 5000.00m,
                            Currency = "PLN",
                            Description = "Default personal cash wallet",
                            Name = "Main Wallet"
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Icon = "wallet",
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Icon = "utensils",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-bc6d-7e8f9a0b1c2d"),
                            Icon = "smartphone",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("d4c3b2a1-f6e5-4b5a-ac6d-9f8e7d6c5b4a"),
                            Icon = "pill",
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-123456789012"),
                            Icon = "bus",
                            Name = "Transport"
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            AccountId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Amount = -150.50m,
                            CategoryId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Date = new DateTime(2024, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grocery"
                        },
                        new
                        {
                            Id = new Guid("d290f1ee-6c89-4b20-bc5e-333333333333"),
                            AccountId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Amount = 3000.00m,
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Date = new DateTime(2024, 5, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transfer"
                        },
                        new
                        {
                            Id = new Guid("a555e888-4444-4444-4444-111122223333"),
                            AccountId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Amount = -45.00m,
                            CategoryId = new Guid("d4c3b2a1-f6e5-4b5a-ac6d-9f8e7d6c5b4a"),
                            Date = new DateTime(2024, 5, 22, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Pharmacy"
                        });
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Fluxo.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fluxo.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Fluxo.Domain.Entities.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
